package com.example.spring_ai_mcp_server.controller;

import java.util.Map;

import org.springframework.ai.chat.client.ChatClient;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.example.spring_ai_mcp_server.service.SemanticCachedService;

@RestController
@RequestMapping("/api/agent/optimized")
public class OptimizedAgentController {
    private final ChatClient chatClient;
    private final SemanticCachedService service;

    // constructor
    public OptimizedAgentController(ChatClient.Builder chatBuilder, SemanticCachedService service) {
        this.service = service;
        this.chatClient = chatBuilder.defaultSystem("You are a high-efficiency enterprise technical assistant.")
                .build();
    }

    @GetMapping("/ask")
    public Map<String, Object> askAgent(@RequestParam(defaultValue = "Tell me about my account status") String query) {
        long startTime = System.currentTimeMillis();

        // Cached_response
        String cachedresponse = service.getResponseIfSimiliar(query);
        // To mitigate NotNull excption
        String safeResponse = (cachedresponse != null && !cachedresponse.isBlank()) ? cachedresponse
                : "No response generated by model.";

        // 3. Put into cache only if it is a valid non-empty response
        if (cachedresponse != null && !cachedresponse.isBlank()) {
            service.put(query, safeResponse);
        }

        // 1)Inspect semantic Cache Layer
        if (cachedresponse != null) {

            return Map.of("query", query,
                    "response", cachedresponse,
                    "latencyMs", (System.currentTimeMillis() - startTime),
                    "source:", "SEMANTIC_CACHE");

        }
        // 2)Cache missed:dispatch upstream to LLM(groq)
        String response = chatClient.prompt().user(query).call().content();

        // 3)Store fresh semantic embeding for subsequent query
        service.put(cachedresponse, response);

        return Map.of(
                "query", query,
                "response", response != null ? response : "No response generated",
                "Latency Ms.", (System.currentTimeMillis() - startTime),
                "source:", "UPSTREAM-LLM");
    }

}
